models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def init_app(app):
    print(app.config["SQLALCHEMY_DATABASE_URI"])
    db.init_app(app)
    with app.app_context():
        db.create_all()

models/folios.py
from . import db


class Folio(db.Model):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )

    name = db.Column(db.String)
    email = db.Column(db.String)

    biography = db.Column(db.String)
    education = db.Column(db.String)

models/users.py
from flask_login import UserMixin
from . import db


class User(db.Model, UserMixin):
    id = db.Column(
        db.BigInteger().with_variant(db.Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    password = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String)

    first_name = db.Column(db.String)
    last_name = db.Column(db.String)

forms/accounts.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators


class LoginForm(FlaskForm):
    email = StringField(
        "name", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = StringField(
        "password",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3, message="มากกว่า 3"),
        ],
    )


class RegisterForm(FlaskForm):
    email = StringField(
        "email", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    password = StringField(
        "password",
        validators=[
            validators.DataRequired(),
            validators.Length(min=3, message="มากกว่า 3"),
        ],
    )
    first_name = StringField("first_name", validators=[validators.DataRequired()])
    last_name = StringField("password", validators=[validators.DataRequired()])

forms/folios.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import validators
from wtforms import widgets


class FolioForm(FlaskForm):
    email = StringField(
        "email", validators=[validators.DataRequired(), validators.Length(min=3)]
    )
    name = StringField("Name", validators=[validators.DataRequired()])
    biography = StringField("Biography", widget=widgets.TextArea())
    education = StringField("Education", widget=widgets.TextArea())

main.py
from flask import Flask, render_template, redirect, url_for
from flask_login import LoginManager

from views import accounts
from views import folios
import models
from models import users

import os

login_manager = LoginManager()
login_manager.login_view = "accounts.login"


@login_manager.unauthorized_handler
def unauthorized():
    # do stuff
    # return "You don't have permission"
    print("You don't have permission")
    return redirect(url_for("accounts.login"))


app = Flask(__name__)


@login_manager.user_loader
def load_user(user_id):
    user = models.db.session.query(users.User).filter_by(id=user_id).first()
    return user


@app.route("/")
def index():
    return render_template("main/index.html")


if __name__ == "__main__":
    app.secret_key = "123456"  # import os // os.get_env['SECRET_KEY']
    login_manager.init_app(app)

    # app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///:memory"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{os.getcwd()}/db/project.db"
    models.init_app(app)

    app.register_blueprint(accounts.bp)
    app.register_blueprint(folios.bp)

    app.run(debug=True)

views/accounts.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, login_user, logout_user

from werkzeug.security import generate_password_hash, check_password_hash

from forms import accounts as accounts_form
import models
from models import users, folios

bp = Blueprint("accounts", __name__, url_prefix="/accounts")


@bp.route("/login")
def login():
    form = accounts_form.LoginForm()
    return render_template("/accounts/login.html", form=form)


@bp.route("/do-login", methods=["POST"])
def do_login():
    # email = request.form.get("email")
    # password = request.form.get("password")

    # print("-->", email, password)
    # print(request.form)

    form = accounts_form.LoginForm()

    if not form.validate_on_submit():
        return redirect(url_for("accounts.login", **form.errors))

    user = (
        models.db.session.query(users.User)
        .filter_by(
            email=form.email.data,
        )
        .first()
    )

    if not user:
        return redirect(url_for("accounts.login", message="invalid login"))

    if not check_password_hash(user.password, form.password.data):
        return redirect(url_for("accounts.login", message="invalid password"))

    login_user(user)

    return redirect(url_for("accounts.dashboard"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    form = accounts_form.RegisterForm()
    if not form.validate_on_submit():
        return render_template("/accounts/register.html", form=form)

    user = users.User()
    form.populate_obj(user)

    print(form.data)
    user.password = generate_password_hash(form.password.data, method="sha256")

    # db management
    models.db.session.add(user)
    models.db.session.commit()

    return redirect(url_for("accounts.login"))


@bp.route("/logout")
def logout():
    logout_user()
    return redirect("/")


@bp.route("/dashboard")
@login_required
def dashboard():
    folio_data = models.db.session.query(folios.Folio).all()
    return render_template("/accounts/dashboard.html", folio_data=folio_data)

views/folios.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, login_user, logout_user

from werkzeug.security import generate_password_hash, check_password_hash

from forms import folios as folios_form
import models
from models import folios

bp = Blueprint("folios", __name__, url_prefix="/folios")


@bp.route("/create", methods=["GET", "POST"])
def create():
    form = folios_form.FolioForm()
    if not form.validate_on_submit():
        return render_template("/folios/create.html", form=form)

    folio = folios.Folio()
    form.populate_obj(folio)

    models.db.session.add(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>/update", methods=["GET", "POST"])
def update(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    form = folios_form.FolioForm(obj=folio)
    if not form.validate_on_submit():
        return render_template("/folios/create.html", form=form)

    form.populate_obj(folio)

    # models.db.session.update(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>/delete")
@login_required
def delete(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    models.db.session.delete(folio)
    models.db.session.commit()

    return redirect(url_for("accounts.dashboard"))


@bp.route("/<folio_id>")
@login_required
def view(folio_id):
    folio = (
        models.db.session.query(folios.Folio)
        .filter_by(
            id=folio_id,
        )
        .first()
    )

    return render_template("/folios/view.html", folio=folio)

templates/accounts/dashboard.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Dashboard Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/5f794aa19f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://kit.fontawesome.com/5f794aa19f.css" crossorigin="anonymous">   
     <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      .my_SP
      {
        background-image: url("https://c4.wallpaperflare.com/wallpaper/509/716/1010/red-spiderman-spider-web-wallpaper-preview.jpg");
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow my_SP">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">SpiderFolio<i class="fa-sharp fa-solid fa-spider" style="margin-left: 5px
    ;"></i></a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="{{ url_for('accounts.logout') }}">Log out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home" class="align-text-bottom"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('folios.create') }}">
              <span data-feather="file" class="align-text-bottom"></span>
              Create Folios
            </a>
          </li>
         </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
      </div>
  

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Biography</th>
      <th scope="col">Education</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for folio in folio_data %}
    <tr>
      <th scope="row">{{ folio.id }}</th>
      <td>{{ folio.name }}</td>
      <td>{{ folio.email }}</td>
      <td>{{ folio.biography }}</td>
      <td>{{ folio.education }}</td>
      <td>
        <a href="{{ url_for('folios.view', folio_id=folio.id) }}" class="btn btn-primary">View</a>
        <a href="{{ url_for('folios.update', folio_id=folio.id) }}" class="btn btn-warning">Edit</a>
        <a href="{{ url_for('folios.delete', folio_id=folio.id) }}" class="btn btn-danger">Delete</a>
      </td>
    </tr>
  {% endfor %}

  </tbody>
</table>

    </main>
  </div>
</div>

 </body>
</html>

templates/accounts/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5f794aa19f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://kit.fontawesome.com/5f794aa19f.css" crossorigin="anonymous">
  </head>
<style>
html,
body {
  height: 100%;
}

body {
  display: flex;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  max-width: 330px;
  padding: 15px;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

</style>

  <body>
    <div class="container">

<div class="text-center">
<main class="form-signin w-100 m-auto">
  <form action="{{ url_for('accounts.do_login') }}" method="POST">
    {{ form.hidden_tag() }}
    <img class="mb-4" src="https://www.pngitem.com/pimgs/m/273-2738704_user-login-png-transparent-logo-twitter-blanco-png.png" alt="" width="150">
    <h1 class="h3 mb-3 fw-normal">SIGN IN</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <div class="row" style="padding-top: 5px;">
      <button class="text-bg-dark p-3" type="submit" >Sign in
        <i class='fas fa-sign-in-alt' style="margin-left: 5px;" ></i></button>
    </div>
    <div class="row" style="padding-top: 5px;">
      <a class="text-bg-dark p-3" href="{{ url_for('accounts.register') }}">
        Register<i class="fa-solid fa-pen" style="margin-left: 5px;"></i></a>
    </div>
  </form>
  
  {% if request.args | length > 0 %}
    <div  class="alert alert-danger" role="alert" style="margin-top: 10px;">
      <ul>
      {% for k, v in request.args.items() %}
        <li><b>{{ k }}: </b> {{ v }}</li>
      {% endfor %}
      </ul>
    </div>
  {% endif %}

</main>
</div>

    </div>
  </body>
</html>

templates/base/nav.html
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('accounts.dashboard') }}">
              <span data-feather="home" class="align-text-bottom"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('folios.create') }}">
              <span data-feather="file" class="align-text-bottom"></span>
              Create Folios
            </a>
          </li>
         </ul>
      </div>
    </nav>

templates/folios/create.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Dashboard Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/5f794aa19f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://kit.fontawesome.com/5f794aa19f.css" crossorigin="anonymous">   
     <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      .my_SP
      {
        background-image: url("https://c4.wallpaperflare.com/wallpaper/509/716/1010/red-spiderman-spider-web-wallpaper-preview.jpg");
      }
    </style>


    
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow my_SP">
  
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">SpiderFolio<i class="fa-sharp fa-solid fa-spider" style="margin-left: 5px
    ;"></i></a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="{{ url_for('accounts.logout') }}">Log out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    {% include "/base/nav.html" %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
      </div>

      <form method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3">
          {{ form.name.label(class_="form-label") }}
          {{ form.name(class_="form-control") }}
        </div>
        <div class="mb-3">
          {{ form.email.label(class_="form-label") }}
          {{ form.email(class_="form-control") }}
        </div>
        <div class="mb-3">
          {{ form.biography.label(class_="form-label") }}
          {{ form.biography(class_="form-control") }}
        </div>
        <div class="mb-3">
          {{ form.education.label(class_="form-label") }}
          {{ form.education(class_="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

      </form>

    </main>
  </div>
</div>

 </body>
</html>

templates/main/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>HomePage</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5f794aa19f.js" crossorigin="anonymous"></script>\
    <link rel="stylesheet" href="https://kit.fontawesome.com/5f794aa19f.css" crossorigin="anonymous">
    
    
    <style> 
      body {
        background-image: url("https://images.hdqwalls.com/download/spiderman-dark-illustration-4k-w8-1920x1080.jpg");
        background-color: #cccccc;
      }
      .my_SP
      {
        background-image: url("https://c4.wallpaperflare.com/wallpaper/509/716/1010/red-spiderman-spider-web-wallpaper-preview.jpg");
      }
      </style>
  </head>
  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow my_SP">
  
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">SpiderFolio<i class="fa-sharp fa-solid fa-spider" style="margin-left: 5px
    ;"></i></a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a class="nav-link px-3" href="https://www.facebook.com/poomipoom/">Contact Us</a>
      </div>
    </div>
  </header>
  <body>
    <div class="container">
    <div class="text-center">
      <main class="form-signin w-100 m-auto">
      <h1 class="h3 mb-3 fw-normal" style="font-weight: 300;color: #9000fef1;"> Selelct For Click </h1>
      <a class="btn btn-danger btn-lg" href="{{ url_for('accounts.login') }}">Login</a>
      <a class="btn btn-danger btn-lg" href="{{ url_for('accounts.register') }}">Register</a>
      </main>
    </div>
    <h1 style="color: #ffffff;;">HI I'M Beginner Developer</h1>
    <img src="https://i.pinimg.com/736x/a7/75/7d/a7757d48ca84ebe259d8c85575437966.jpg" alt="EX" width="500">
    </div>
  </body>
</html>